#!/usr/bin/env python3
"""Compile PLAN.md from the P0 section of data-flow-v2-artifact.html.

The page is the source of truth for the plan; this extracts §P0 into a
standalone markdown plan (ordered changes become a task list). Edit the
page, then rerun. Never edit PLAN.md by hand.
"""
from html.parser import HTMLParser
from pathlib import Path
import re

HERE = Path(__file__).parent
SRC = HERE / "data-flow-v2-artifact.html"
DST = HERE / "PLAN.md"

html = SRC.read_text()
start = html.index('<section id="p0">')
end = html.index("</section>", start) + len("</section>")
fragment = html[start:end]


class PlanMD(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.lines = []
        self.buf = None      # inline buffer while inside h2/h3/p/li/td
        self.lists = []      # stack of ["ul"] or ["ol", counter, is_rank]
        self.row = None      # cells of the current table body row
        self.in_thead = False
        self.in_why = False  # the sechead's "why" kicker span

    def emit(self, line=""):
        self.lines.append(line)

    def text_of(self):
        t = re.sub(r"\s+", " ", "".join(self.buf)).strip()
        self.buf = None
        return re.sub(r"\*\*\s+", "** ", re.sub(r"\s+\*\*", " **", t))

    def handle_starttag(self, tag, attrs):
        cls = dict(attrs).get("class", "")
        if tag in ("h2", "h3", "p", "li"):
            self.buf = []
        elif tag == "ul":
            self.lists.append(["ul"])
        elif tag == "ol":
            self.lists.append(["ol", 0, "rank" in cls])
        elif tag == "thead":
            self.in_thead = True
        elif tag == "tr" and not self.in_thead:
            self.row = []
        elif tag == "td" and self.row is not None:
            self.buf = []
        elif tag == "span" and "why" in cls and self.buf is None:
            self.buf = []
            self.in_why = True
        elif self.buf is not None:
            if tag == "code":
                self.buf.append("`")
            elif tag in ("strong", "b"):
                self.buf.append("**")
            elif tag in ("em", "i"):
                self.buf.append("*")

    def handle_endtag(self, tag):
        if tag == "h2" and self.buf is not None:
            self.emit("# " + self.text_of())
            self.emit()
        elif tag == "h3" and self.buf is not None:
            self.emit("## " + self.text_of())
            self.emit()
        elif tag == "p" and self.buf is not None:
            t = self.text_of()
            if t:
                self.emit(t)
                self.emit()
        elif tag == "li" and self.buf is not None:
            t = self.text_of()
            pad = "  " * max(len(self.lists) - 1, 0)
            top = self.lists[-1] if self.lists else ["ul"]
            if top[0] == "ol":
                top[1] += 1
                mark = f"- [ ] {top[1]}." if top[2] else f"{top[1]}."
                self.emit(f"{pad}{mark} {t}")
            else:
                self.emit(f"{pad}- {t}")
        elif tag in ("ul", "ol"):
            if self.lists:
                self.lists.pop()
            if not self.lists:
                self.emit()
        elif tag == "span" and self.in_why and self.buf is not None:
            self.emit("*" + self.text_of() + "*")
            self.emit()
            self.in_why = False
        elif tag == "thead":
            self.in_thead = False
        elif tag == "td" and self.buf is not None and self.row is not None:
            self.row.append(self.text_of())
        elif tag == "tr" and self.row is not None:
            c = self.row + ["", "", ""]
            self.emit(f"- {c[0]}")
            if c[1]:
                self.emit(f"  - evidence: {c[1]}")
            if c[2]:
                self.emit(f"  - replace with: {c[2]}")
            self.row = None
        elif tag == "table":
            self.emit()
        elif self.buf is not None:
            if tag == "code":
                self.buf.append("`")
            elif tag in ("strong", "b"):
                self.buf.append("**")
            elif tag in ("em", "i"):
                self.buf.append("*")

    def handle_data(self, data):
        if self.buf is not None:
            self.buf.append(data)


parser = PlanMD()
parser.feed(fragment)

banner = (
    "<!-- GENERATED from data-flow-v2-artifact.html §P0 by compile-plan.py."
    " Edit the page, then rerun. Do not edit this file by hand. -->\n\n"
)
body = "\n".join(parser.lines).strip() + "\n"
assert body.startswith("# "), "P0 title not extracted"
assert body.count("- [ ]") == 10, "expected 10 ordered changes"
DST.write_text(banner + body)
print(f"wrote {DST.name}: {DST.stat().st_size:,} bytes, "
      f"{body.count(chr(10))} lines, {body.count('- [ ]')} tasks")
