"""Executable interfaces for the Regulatory Evidence Framework."""

from importlib.metadata import PackageNotFoundError, version

from refspec.accepted_output import (
    AcceptedOutputAuthorization,
    AcceptedOutputAuthorizationError,
    authorize_accepted_assignment,
)
from refspec.atlas.release_acceptance import (
    RELEASE_ACCEPTANCE_TYPE,
    RELEASE_ACCEPTANCE_VERSION,
    AcceptanceCheckStatus,
    ReleaseAcceptanceError,
    ReproducibilityStatus,
    VocabularyAtlasReleaseAcceptance,
    build_vocabulary_atlas_release_acceptance,
)
from refspec.generated_rulespec_dependency import load_rulespec_dependency
from refspec.managed_release import (
    CANDIDATE_EXCLUDED_SOURCE_STATUSES,
    ManagedReleaseAuthorizationError,
    ManagedReleaseCandidatePermission,
    ManagedReleaseConceptMapping,
    ManagedReleaseError,
    ManagedReleaseExpression,
    ManagedReleaseGraphFactsView,
    ManagedReleaseIdentityLink,
    ManagedReleaseLifecycleParticipant,
    ManagedReleaseMember,
    ManagedReleaseRelation,
    ManagedReleaseView,
)
from refspec.vocabulary import (
    CANONICAL_JSON_POLICY,
    CONCEPT_EVENT_PARTICIPANT_COLUMNS,
    CONCEPT_LABEL_COLUMNS,
    CONCEPT_RELATION_COLUMNS,
    MAPPING_IMPORT_REQUIRED_FEATURES,
    REQUIRED_IMPORT_FEATURES,
    ConceptEventParticipant,
    ConceptLabel,
    ConceptRelation,
    CoverageException,
    EnrichmentConfiguration,
    EnrichmentDeploymentDecision,
    EnrichmentEvaluationResult,
    EnrichmentProfile,
    ImportFeatureCoverage,
    IndexedVocabularyExpression,
    LegacyMigrationBatch,
    OutputProfile,
    ReferenceRuntimeError,
    ReferenceRuntimeStore,
    RegistryDeploymentDecision,
    RegistryImportCoverageReport,
    RegistryReconciliationReport,
    VocabularyUniverseFreeze,
    adapt_source_terms_for_migration,
    assert_managed_vocabulary_row_integrity,
    bind_ranked_candidates,
    canonical_payload_digest,
    canonical_text_digest,
    indexed_expression_corpus_digest,
    indexed_expression_id,
    indexed_expression_id_set_digest,
    indexed_expression_identity,
    indexed_expression_identity_from_record,
    indexed_expression_identity_set_digest,
    materialize_open_label_value_assertion,
    migrate_legacy_concepts,
    normalize_unicode_text,
    reject_legacy_conforming_payload,
    require_language_tag,
    require_payload_digest,
    require_vocabulary_universe_freeze,
    seal_payload,
)

try:
    __version__ = version("refspec")
except PackageNotFoundError:  # pragma: no cover - direct source-tree import
    __version__ = "0.1.0.dev0"

__all__ = [
    "CANDIDATE_EXCLUDED_SOURCE_STATUSES",
    "CANONICAL_JSON_POLICY",
    "CONCEPT_EVENT_PARTICIPANT_COLUMNS",
    "CONCEPT_LABEL_COLUMNS",
    "CONCEPT_RELATION_COLUMNS",
    "MAPPING_IMPORT_REQUIRED_FEATURES",
    "RELEASE_ACCEPTANCE_TYPE",
    "RELEASE_ACCEPTANCE_VERSION",
    "REQUIRED_IMPORT_FEATURES",
    "AcceptanceCheckStatus",
    "AcceptedOutputAuthorization",
    "AcceptedOutputAuthorizationError",
    "ConceptEventParticipant",
    "ConceptLabel",
    "ConceptRelation",
    "CoverageException",
    "EnrichmentConfiguration",
    "EnrichmentDeploymentDecision",
    "EnrichmentEvaluationResult",
    "EnrichmentProfile",
    "ImportFeatureCoverage",
    "IndexedVocabularyExpression",
    "LegacyMigrationBatch",
    "ManagedReleaseAuthorizationError",
    "ManagedReleaseCandidatePermission",
    "ManagedReleaseConceptMapping",
    "ManagedReleaseError",
    "ManagedReleaseExpression",
    "ManagedReleaseGraphFactsView",
    "ManagedReleaseIdentityLink",
    "ManagedReleaseLifecycleParticipant",
    "ManagedReleaseMember",
    "ManagedReleaseRelation",
    "ManagedReleaseView",
    "OutputProfile",
    "ReferenceRuntimeError",
    "ReferenceRuntimeStore",
    "RegistryDeploymentDecision",
    "RegistryImportCoverageReport",
    "RegistryReconciliationReport",
    "ReleaseAcceptanceError",
    "ReproducibilityStatus",
    "VocabularyAtlasReleaseAcceptance",
    "VocabularyUniverseFreeze",
    "__version__",
    "adapt_source_terms_for_migration",
    "assert_managed_vocabulary_row_integrity",
    "authorize_accepted_assignment",
    "bind_ranked_candidates",
    "build_vocabulary_atlas_release_acceptance",
    "canonical_payload_digest",
    "canonical_text_digest",
    "indexed_expression_corpus_digest",
    "indexed_expression_id",
    "indexed_expression_id_set_digest",
    "indexed_expression_identity",
    "indexed_expression_identity_from_record",
    "indexed_expression_identity_set_digest",
    "load_rulespec_dependency",
    "materialize_open_label_value_assertion",
    "migrate_legacy_concepts",
    "normalize_unicode_text",
    "reject_legacy_conforming_payload",
    "require_language_tag",
    "require_payload_digest",
    "require_vocabulary_universe_freeze",
    "seal_payload",
]
