import pandas as pd, json
df = pd.read_parquet("/Users/mikewolfd/.claude/jobs/9dfc0c64/tmp/inv-universe/scratch/legal_authorities_slim.parquet")
hits = pd.read_json("/Users/mikewolfd/.claude/jobs/9dfc0c64/tmp/inv-universe/scratch/shape_a_hits.json")
idxs = hits["idx"].tolist()
sub = df.loc[idxs].copy()
sub["part_dot_section"] = hits.set_index("idx").loc[idxs, "part"].astype(str) + "." + hits.set_index("idx").loc[idxs, "section"].astype(str)

print("== shape (a) reg-shaped: rows/texts/RINs ==")
print("rows:", len(sub))
print("distinct authority_text:", sub["authority_text"].nunique())
print("distinct RINs:", sub["rin"].nunique())
print()
print("== verdict/note crosstab ==")
print(sub.groupby(["usc_section_verdict","authority_in_own_cfr_note"], dropna=False).size())
print()
print("== corroboration_rule counts ==")
print(sub["corroboration_rule"].value_counts(dropna=False))
print()
print("== usc_section_corrected non-null count ==")
print(sub["usc_section_corrected"].notna().sum())
print()
print("distinct authority_text list with counts:")
g = sub.groupby("authority_text").agg(rows=("rin","size"), rins=("rin","nunique")).reset_index()
print(g.sort_values("rows", ascending=False).to_string())
sub.to_json("/Users/mikewolfd/.claude/jobs/9dfc0c64/tmp/inv-universe/scratch/shape_a_full.json", orient="records", indent=2)
