import pandas as pd
sub = pd.read_json("/Users/mikewolfd/.claude/jobs/9dfc0c64/tmp/inv-universe/scratch/shape_c_full.json")
narrow = sub[sub.is_real_section == False].copy()
print("== shape (c) chapter-only (no real section by that number): rows/texts/RINs ==")
print("rows:", len(narrow), "distinct authority_text:", narrow.authority_text.nunique(), "distinct RINs:", narrow.rin.nunique())
print()
print("verdict/note crosstab:")
print(narrow.groupby(["usc_section_verdict","authority_in_own_cfr_note"], dropna=False).size())
print()
print("usc_title distribution:")
print(narrow.usc_title.value_counts())
print()
g = narrow.groupby(["usc_title","usc_section","authority_text"]).agg(rows=("rin","size"), rins=("rin","nunique")).reset_index()
pd.set_option("display.max_rows", 200)
pd.set_option("display.width", 220)
print(g.sort_values(["rows"], ascending=False).head(60).to_string())
narrow.to_json("/Users/mikewolfd/.claude/jobs/9dfc0c64/tmp/inv-universe/scratch/shape_c_narrow.json", orient="records", indent=2)
