#!/usr/bin/env python3
"""Refresh the RuleSpec-owned adjudication shapes vendored into this binding.

The binding validator deliberately imports no RefSpec or RuleSpec package
code. This development-time generator is the only package-aware side of that
boundary: it reads compiler output through the installed
``rulespec_conformance.contract.resources`` accessor, writes plain Turtle
beside the Atlas shapes, and records exact source and output digests.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from rulespec_conformance.contract import VERSION, resources

BINDING_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = BINDING_ROOT / "shapes" / "rulespec-adjudication.shacl.ttl"
LOCK_PATH = BINDING_ROOT / "shapes" / "rulespec-adjudication.lock.json"
RESOURCE_NAMES = ("machine-adjudication", "resolver-proof-record")


def _digest(payload: bytes) -> str:
    return "sha256:" + hashlib.sha256(payload).hexdigest()


def _canonical_json(value: object) -> bytes:
    return (
        json.dumps(
            value,
            ensure_ascii=False,
            allow_nan=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
        + b"\n"
    )


def render() -> tuple[bytes, bytes]:
    parts = [
        "# GENERATED by tools/refresh_rulespec_adjudication_shapes.py.",
        "# Source: rulespec-conformance compiler output; do not edit here.",
        f"# Rulespec contract version: {VERSION}",
        "",
    ]
    source_rows: list[dict[str, object]] = []
    for name in RESOURCE_NAMES:
        text = resources.shacl_sparql(name, family="analysis")
        payload = text.encode("utf-8")
        source_rows.append(
            {
                "accessor": (
                    "rulespec_conformance.contract.resources."
                    f"shacl_sparql({name!r}, family='analysis')"
                ),
                "byteLength": len(payload),
                "digest": _digest(payload),
                "name": name,
            }
        )
        parts.extend((text.rstrip(), ""))
    output = "\n".join(parts).encode("utf-8")
    lock = _canonical_json(
        {
            "format": "RulespecAdjudicationShapeLock",
            "formatVersion": "1.0",
            "output": {
                "byteLength": len(output),
                "digest": _digest(output),
                "path": "shapes/rulespec-adjudication.shacl.ttl",
            },
            "package": "rulespec-conformance",
            "packageVersion": VERSION,
            "resources": source_rows,
        }
    )
    return output, lock


def _check(path: Path, expected: bytes) -> bool:
    if not path.is_file():
        print(f"STALE: {path.relative_to(BINDING_ROOT)} is missing")
        return False
    observed = path.read_bytes()
    if observed != expected:
        print(
            f"STALE: {path.relative_to(BINDING_ROOT)} differs "
            f"(expected {_digest(expected)}, found {_digest(observed)})"
        )
        return False
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="refuse stale generated data instead of refreshing it",
    )
    args = parser.parse_args()
    output, lock = render()
    if args.check:
        return 0 if _check(OUTPUT_PATH, output) and _check(LOCK_PATH, lock) else 1
    OUTPUT_PATH.write_bytes(output)
    LOCK_PATH.write_bytes(lock)
    print(
        "refreshed "
        f"{OUTPUT_PATH.relative_to(BINDING_ROOT)} ({_digest(output)}) and "
        f"{LOCK_PATH.relative_to(BINDING_ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
